### ISSUE TITLE
NetStandard Version

### ISSUE THREAD

**Issue by jferreirasetesys** [ela-compil/BACnet#29]
It would be a good solution to have a Net Standard version of the SDK. I think the only problem will be with serial port. One nice solution would be to have a base DLL compiled with Net Standard, and a Net 4.0 DLL based on that solution, adding the Serial Port MSTP implementation.
It could allow the Bacnet IP implementation on Linux, Mac, Xamarin, etc.

**Comment by gralin** [comment]
@jferreirasetesys I agree, .NET Standard is the way to go with new projects, and libraries like this should be made compatible. Is anyone willing to contribute to this?

**Comment by jferreirasetesys** [comment]
I actually already compiled it sucessfuly. It is just a matter of removing the MSTP components. I think the problem is more on the way it should be organized. With that solved i will gladly help.

**Comment by maikebing** [comment]
#31  Update to netstandard2 and new project format
