### ISSUE TITLE
Hi the whois return 255.255.255.255 

### ISSUE THREAD

**Issue by pigwing** [ela-compil/BACnet#5]
in my compuer whois return UnicastAddresses 255.255.255.255
and i send the correct who is length is 54 bug it is 50

**Comment by pigwing** [comment]
in my computer Broadcast is not found , it is default 255.255.255.255, so i must bacnet_client.WhoIs(receiver: new BacnetAddress(BacnetAddressTypes.IP, "192.168.199.255", 0xFFFF));

**Comment by pigwing** [comment]
GetBroadcastAddress has bug

**Comment by pigwing** [comment]
but IPAddress.Broadcast is 255.255.255.255

**Comment by gralin** [comment]
@pigwing thanks for the info. I'm swamped at work so can't look it up but if you could send me a pull request I will investigate.

**Comment by gralin** [comment]
@pigwing I took a loot at the code that generates the broadcast address and it works for me. Are you setting your local endpoint address when creating the client object?

**Comment by gralin** [comment]
@pigwing do you have any more info about the bug you are refering to or can I close this?

**Comment by gralin** [comment]
Closed due to inactivity
