### ISSUE TITLE
How to change the Source port ?

### ISSUE THREAD

**Issue by dibrony** [ela-compil/BACnet#66]
Hi,

Each time I run the application i have a new random source port while the destination port is always 47808.
How can I fix the source port ? I need it to be 47808 as well.

Thank you

**Comment by gralin** [comment]
Hi @dibrony, you need to set `useExclusivePort` on the transport to `true` and specify the port you want to use.

```csharp
var localPort = 0xBAC0;
var localEndpointIp = "192.168.1.2";

var transport = new BacnetIpUdpProtocolTransport(
    localPort, useExclusivePort: true, localEndpointIp: localEndpointIp);

var client = new BacnetClient(transport);
```

This is the same setting you need to change in Yabe the first time you use it, so it always uses the same source UDP port.

![image](https://user-images.githubusercontent.com/3457048/105191179-1515a100-5b37-11eb-9fe3-705076477d61.png)

**Comment by ameyaalpha** [comment]
Which BACnet protocol version does the stack support? Has any of the device using the stack gone through BTL testing? Can you please let us know?

**Comment by gralin** [comment]
@ameyaalpha please open a new issue as this question is not related to this topic

**Comment by ameyaalpha** [comment]
OK thanks @gralin
